--- !test_ddpm
dim: 64

betas_low: 0.0001
betas_high: 0.01
T: 1000

epochs: 400

ema_weight: 0.9999
ema_warmup: 1

ddim: !ddim
  eta: 0.0
  n_steps: 50

unet_config: !unet_config
  dim: 32
  out_dim: 3
  mults:
    - 1
    - 2
    - 4
    - 8
  attention_layers:
    - 4
    - 8
  resblock_groups: 8